### ISSUE TITLE
Select Top values

### ISSUE THREAD

**Issue by deus82ex** [mladenb/sql-query-builder#4]
Hi,

is it possible to add the possibility to select top n values?
If I use "Select" I cann ad "TOP(n)" as parameter but on SelectAll you cant.
An Extension Top(count) would be great.

Regards Mario

**Comment by mladenb** [comment]
I've added such a feature. Thanks for pointing it out. It's added in the commit 0379e18.

**Comment by deus82ex** [comment]
When will the nuget package be updated?

**Comment by mladenb** [comment]
Nuget.org is going through the integration process with Microsoft's Live.com and currently I'm unable to login to my account to publish the new nuget version (and I didn't download the nuget key to be able to do it directly from my machine - shame on me). So, for the time being, I'm blocked from being able to update the nuget packages or add new ones.

If you like, you can build the nuget package yourself, until this issue is resolved with Microsoft. Just clone this repository and build the SqlQueryBuilder solution (in the Release mode). When you're done, in your bin/Release/ folder you'll find your nuget package(s) already built for you (like SqlQueryBuilder.Core.1.1.0.nupkg).

However, I've pushed a new branch for you, if you find that difficult, so you can just get your nuget there: https://github.com/mladenb/sql-query-builder/tree/for_deus/DefaultSqlQueryBuilder/bin/Release

Cheers :)

**Comment by deus82ex** [comment]
Thanks, I took your release :)
